apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: trading-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: trading.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: trading-frontend
                port:
                  number: 80
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: trading-backend
                port:
                  number: 4000


